server:
    port: ${SERVER_PORT}
    
spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: ${DB_LOCAL_URL}
        username: ${DB_USER}
        password: ${DB_ROOT_PASSWORD}
        driver-class-name: ${DB_DRIVER_CLASS_NAME}
    mustache:  
        check-template-location: false
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: ${DB_DIALECT}
        open-in-view: false
        show-sql: false
        defer-datasource-initialization: false
    sql:
        init:
            mode: never
